package authtemplate.infrastructure.security.exception

import authtemplate.infrastructure.common.exception.BasicException

class RefreshTokenNotMatchException : BasicException(AuthStatusCode.REFRESH_TOKEN_NOT_MATCH)